### ISSUE TITLE
Cinematics errors [CinematicStudio] Disabling CinematicStudio v2.0.1-indev-1 on 1.21.1

### ISSUE THREAD

**Issue by NontapatL** [PluginBugs/Issues-CinematicStudio#100]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

siandwa

### What happened?

i put plugin on 1.21.1 but its not work

my itemadders is work but cinematics not work

### Steps to reproduce the issue

1. put plugin in plugin folder
2. start server

### Server version

 This server is running Paper version 1.21.1-97-master@acdd6d3 (2024-09-23T22:14:51Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### CinematicsStudio Version

CinematicStudio version 2.0.1-indev-1

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-731

### LoneLibs Version

 LoneLibs version 1.0.59

### FULL server log

full log its There was an error creating your Issue: body is too long (maximum is 65536 characters).
then i put it in pastebin

https://pastebin.com/pEvMy0qT

### Error (optional)

```shell
[10:17:12] [Server thread/INFO]: [CinematicStudio] Enabling CinematicStudio v2.0.1-indev-1
[10:17:14] [Server thread/ERROR]: Error occurred while enabling CinematicStudio v2.0.1-indev-1 (Is it up to date?)
java.lang.RuntimeException: java.nio.file.NoSuchFileException: C:\Users\Administrator\Desktop\Eternity%201.21.1\plugins\.paper-remapped\CinematicStudio_2.0.1-indev-1.jar
	at CinematicStudio_2.0.1-indev-1.jar/dev.lone.CinematicStudio.b.a(SourceFile:80) ~[CinematicStudio_2.0.1-indev-1.jar:?]
	at CinematicStudio_2.0.1-indev-1.jar/dev.lone.CinematicStudio.c.a(SourceFile:39) ~[CinematicStudio_2.0.1-indev-1.jar:?]
	at CinematicStudio_2.0.1-indev-1.jar/dev.lone.CinematicStudio.Main.b(SourceFile:75) ~[CinematicStudio_2.0.1-indev-1.jar:?]
	at CinematicStudio_2.0.1-indev-1.jar/dev.lone.CinematicStudio.Main.onEnable(SourceFile:45) ~[CinematicStudio_2.0.1-indev-1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-97-acdd6d3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-97-acdd6d3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-97-acdd6d3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-97-acdd6d3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.1.jar:1.21.1-97-acdd6d3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-97-acdd6d3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-97-acdd6d3]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.nio.file.NoSuchFileException: C:\Users\Administrator\Desktop\Eternity%201.21.1\plugins\.paper-remapped\CinematicStudio_2.0.1-indev-1.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:197) ~[?:?]
	at java.base/java.nio.file.Files.readAttributes(Files.java:1865) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1512) ~[?:?]
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:744) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:254) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:316) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:282) ~[?:?]
	at CinematicStudio_2.0.1-indev-1.jar/dev.lone.CinematicStudio.b.a(SourceFile:58) ~[CinematicStudio_2.0.1-indev-1.jar:?]
	... 13 more
[10:17:14] [Server thread/INFO]: [CinematicStudio] Disabling CinematicStudio v2.0.1-indev-1
```

### CinematicsStudio config.yml

```shell
messages:
  settings:
    lang: "en"
    extract_default_language_files: true
  debug:
    enabled: false
cinematics:
  graphics:
    pumpkin:
      custom_model_data: 3000001
      display_name: ""
    wandering_trader_egg:
      custom_model_data: 3000001
      display_name: ""
gui:
  use_resourcepack: true
```

**Comment by BRASHEXODUS** [comment]
did you get it to work cause im experiencing the same thing with the same paper version aswell

**Comment by NontapatL** [comment]
> did you get it to work cause im experiencing the same thing with the same paper version aswell

its not work anything sir i cannot use anything

**Comment by LoneDev6** [comment]
You have a space in your server folder. Remove it.
Spigot doesn't usually like that.
