### ISSUE TITLE
Unsupported Minecraft 1.20.4

### ISSUE THREAD

**Issue by MattiaFioretti** [PluginBugs/Issues-CinematicStudio#101]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

matithya

### What happened?

The plugin does not work on 1.20.4 with the latest version of LoneLibs and ProtocolLib.

### Steps to reproduce the issue

Self explanatory

### Server version

UniverseSpigot (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) also tried with spigot and paper.

### CinematicsStudio Version

CinematicStudio version 2.0.1-indev-1

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-721

### LoneLibs Version

LoneLibs 1.0.59

### Error (optional)

```shell
[17:49:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cinematic' in plugin CinematicStudio v2.0.1-indev-1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[?:git-UniverseSpigot-"6375a7a"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[?:git-UniverseSpigot-"6375a7a"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1002) ~[?:git-UniverseSpigot-"6375a7a"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[?:git-UniverseSpigot-"6375a7a"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:58) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1475) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:196) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1452) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1375) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1353) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242) ~[?:git-UniverseSpigot-"6375a7a"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[?:git-UniverseSpigot-"6375a7a"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.IDataComponents.setCustomName(org.bukkit.inventory.ItemStack, String)" because "lonelibs.dev.lone.fastnbt.nms.nbt.NBT.dataComponents" is null
        at lonelibs.dev.lone.fastnbt.nms.nbt.NItem.setCustomName(NItem.java:182) ~[LoneLibs.jar:?]
        at dev.lone.CinematicStudio.b.a(SourceFile:196) ~[CinematicStudio_2.0.1-indev-1.jar:?]
        at CinematicStudio.m.R.a(SourceFile:650) ~[CinematicStudio_2.0.1-indev-1.jar:?]
        at CinematicStudio.m.R.ai(SourceFile:256) ~[CinematicStudio_2.0.1-indev-1.jar:?]
        at CinematicStudio.m.R.a(SourceFile:583) ~[CinematicStudio_2.0.1-indev-1.jar:?]
        at CinematicStudio.m.al.a(SourceFile:129) ~[CinematicStudio_2.0.1-indev-1.jar:?]
        at CinematicStudio.m.ai.onCommand(SourceFile:37) ~[CinematicStudio_2.0.1-indev-1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[?:git-UniverseSpigot-"6375a7a"]
        ... 29 more
```

**Comment by MattiaFioretti** [comment]
A fix has been promised for months, please, we paid. @LoneDev6

**Comment by Andre601** [comment]
> A fix has been promised for months, please, we paid. @LoneDev6

Paying for a plugin does not guarantee receiving updates at all.

**Comment by MattiaFioretti** [comment]
> > A fix has been promised for months, please, we paid. @LoneDev6
> 
> Paying for a plugin does not guarantee receiving updates at all.

This is not an update. The plugin says it supports 1.20.4, and in reality it does not work. As a buyer, I have a 1.20.4 server, I read that the plugin supports it and I buy it.

**Comment by MattiaFioretti** [comment]
> > A fix has been promised for months, please, we paid. @LoneDev6
> 
> Paying for a plugin does not guarantee receiving updates at all.

![image](https://github.com/user-attachments/assets/bab807d7-bfc4-4a12-a5cb-69ee5afc8d85)
So please, I would like this to be resolved.

**Comment by Andre601** [comment]
Downgrade LoneLibs and ProtocolLib to an older version. PL in particular needs to be 5.2.0 for versions 1.8 through 1.20.4 And the same may be the case for LoneLibs.
This isn't really a CinematicStudio issue, but an issue of using the wrong dependency versions.

**Comment by Andre601** [comment]
At least for ProtocolLib is it mentioned on its spigot page (And CI) what version you need for what MC versions.

**Comment by LoneDev6** [comment]
Update LoneLibs
