### ISSUE TITLE
Plugin Config doesn't work at all.

### ISSUE THREAD

**Issue by davidgb8246** [PluginBugs/Issues-CinematicStudio#64]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

The config file seems to be corrupt and it's impossible to open it,

![image](https://github.com/PluginBugs/Issues-CinematicStudio/assets/85250523/510289cf-4cd2-4761-a160-53e644fe3b92)

### Steps to reproduce the issue

1. Download the plugin and all requirements.
2. Use Paper 1.20.2 Server JAR (git-paper-261)
3. Start the server.

### Server version

Paper 1.20.2 Server JAR (git-paper-261)

### CinematicsStudio Version

CinematicStudio version 1.4.6

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-673

### LoneLibs Version

LoneLibs version 1.0.42

### FULL server log

There are no errors on the console.

### Error (optional)

```shell
This warn happend when you run the command: "/cin play"

[19:10:18 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[19:10:18 WARN]:        at CinematicStudio_1.4.6.jar//dev.lone.cinematicstudio.commandhandler.MasterCommand.lambda$loadSubCommands$3(SourceFile:156)
[19:10:18 WARN]:        at CinematicStudio_1.4.6.jar//dev.lone.cinematicstudio.commandhandler.Subcommand.playerExecutes(SourceFile:160)
[19:10:18 WARN]:        at CinematicStudio_1.4.6.jar//dev.lone.cinematicstudio.commandhandler.Subcommand.checkPlayerExecutes(SourceFile:152)
[19:10:18 WARN]:        at CinematicStudio_1.4.6.jar//dev.lone.cinematicstudio.commandhandler.MasterCommand.onCommand(SourceFile:330)
[19:10:18 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:10:18 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[19:10:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[19:10:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[19:10:18 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[19:10:18 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[19:10:18 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[19:10:18 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[19:10:18 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[19:10:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[19:10:18 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[19:10:18 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:10:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:10:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:10:18 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[19:10:18 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[19:10:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:10:18 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[19:10:18 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[19:10:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:10:18 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[19:10:18 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[19:10:18 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[19:10:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

### CinematicsStudio config.yml

```shell
File broken!
```

**Comment by LoneDev6** [comment]
This is a leftover, the plugin has no settings, do not use this file.

About the error, you're missing some arguments.
The play command requires a cinematic name to be set, you're using none.
