### ISSUE TITLE
[INDEV] Chat click event sends error in console

### ISSUE THREAD

**Issue by Asleeepp** [PluginBugs/Issues-CinematicStudio#80]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

asleepp

### What happened?

clicking on the [Click] to set location here sends an "An internal error occurred" error

### Steps to reproduce the issue

click on the input command chat thingie

### Server version

Current: git-Purpur-2134 (MC: 1.20.4)*
Previous: git-Purpur-2062 (MC: 1.20.1)

You are 40 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### CinematicsStudio Version

2.0.0-indev-7

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Error (optional)

```shell
01:13:32 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'cinematic' in plugin CinematicStudio v2.0.0-indev-7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:344) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2287) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$17(ServerGamePacketListenerImpl.java:2247) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1488) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1465) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1388) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1366) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1255) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2134]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Failed to calculate length. No next node and 'moveToNextNode: false'!
        at CinematicStudio.m.I.a(SourceFile:75) ~[CinematicStudio_2.0.0-indev-7.jar:?]
        at CinematicStudio.m.z.c(SourceFile:67) ~[CinematicStudio_2.0.0-indev-7.jar:?]
        at CinematicStudio.m.U.a(SourceFile:642) ~[CinematicStudio_2.0.0-indev-7.jar:?]
        at java.util.ArrayList.replaceAllRange(ArrayList.java:1795) ~[?:?]
        at java.util.ArrayList.replaceAll(ArrayList.java:1785) ~[?:?]
        at CinematicStudio.m.U.a(SourceFile:639) ~[CinematicStudio_2.0.0-indev-7.jar:?]
        at CinematicStudio.m.U.f(SourceFile:254) ~[CinematicStudio_2.0.0-indev-7.jar:?]
        at CinematicStudio.m.U.a(SourceFile:581) ~[CinematicStudio_2.0.0-indev-7.jar:?]
        at CinematicStudio.m.ap.a(SourceFile:129) ~[CinematicStudio_2.0.0-indev-7.jar:?]
        at CinematicStudio.m.am.onCommand(SourceFile:37) ~[CinematicStudio_2.0.0-indev-7.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
```

**Comment by LoneDev6** [comment]
Can't reproduce the issue, please try to install the indev-8 after release
