### ISSUE TITLE
CinematicStudio indev-8 not working with 1.20.1 ?

### ISSUE THREAD

**Issue by NontapatL** [PluginBugs/Issues-CinematicStudio#83]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

siandwa

### What happened?

i cannot use CinematicStudio v2.0.0-indev-8 in 1.20.1 version its red and errors

### Steps to reproduce the issue

start server

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### CinematicsStudio Version

CinematicStudio version 2.0.0-indev-8

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

https://pastebin.com/wKMviJLg

### Error (optional)

```shell
[20:01:42] [Server thread/INFO]: [CinematicStudio] Enabling CinematicStudio v2.0.0-indev-8
[20:01:43] [Server thread/ERROR]: [CinematicStudio] Failed to find nms implementation for: interface CinematicStudio.m.aK
[20:01:43] [Server thread/ERROR]: Error occurred while enabling CinematicStudio v2.0.0-indev-8 (Is it up to date?)
java.lang.RuntimeException: null
    at CinematicStudio.m.ar.a(SourceFile:138) ~[CinematicStudio_2.0.0-indev-8.jar:?]
    at CinematicStudio.m.ar.a(SourceFile:46) ~[CinematicStudio_2.0.0-indev-8.jar:?]
    at CinematicStudio.m.ar.a(SourceFile:37) ~[CinematicStudio_2.0.0-indev-8.jar:?]
    at CinematicStudio.m.aL.<init>(SourceFile:15) ~[CinematicStudio_2.0.0-indev-8.jar:?]
    at CinematicStudio.m.aL.a(SourceFile:38) ~[CinematicStudio_2.0.0-indev-8.jar:?]
    at dev.lone.CinematicStudio.Main.onEnable(SourceFile:44) ~[CinematicStudio_2.0.0-indev-8.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.1.jar:git-Paper-196]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
    at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### CinematicsStudio config.yml

```shell
don't have folder CinematicsStudio becuz plugin is red errors
```

**Comment by LoneDev6** [comment]
Update to 1.20.4 or 1.20.3
