### ISSUE TITLE
Error occurred while enabling CinematicStudio

### ISSUE THREAD

**Issue by 44wrw44** [PluginBugs/Issues-CinematicStudio#87]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

The error started to occur after updating the dependencies, I can’t return the dependency versions because I need the latest version of ItemsAdder.

### Steps to reproduce the issue

Use the latest version of the plugin and dependencies. (latest devbuild ProtocolLib)

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2162 (MC: 1.20.4)
* You are running the latest version

### CinematicsStudio Version

Cinematic Studio 2.0.0-indev-8

### ProtocolLib Version

ProtocolLib version 5.2.1-SNAPSHOT-685

### LoneLibs Version

LoneLibs version 1.0.54

### Error (optional)

```shell
[00:00:43] [Server thread/INFO]: [CinematicStudio] Enabling CinematicStudio v2.0.0-indev-8
[00:00:43] [Server thread/ERROR]: [CinematicStudio] Failed to find nms implementation for: interface CinematicStudio.m.aK
[00:00:43] [Server thread/ERROR]: Error occurred while enabling CinematicStudio v2.0.0-indev-8 (Is it up to date?)
java.lang.RuntimeException: null
	at CinematicStudio.m.ar.a(SourceFile:138) ~[CinematicStudio_2.0.0-indev-8.jar:?]
	at CinematicStudio.m.ar.a(SourceFile:46) ~[CinematicStudio_2.0.0-indev-8.jar:?]
	at CinematicStudio.m.ar.a(SourceFile:37) ~[CinematicStudio_2.0.0-indev-8.jar:?]
	at CinematicStudio.m.aL.<init>(SourceFile:15) ~[CinematicStudio_2.0.0-indev-8.jar:?]
	at CinematicStudio.m.aL.a(SourceFile:38) ~[CinematicStudio_2.0.0-indev-8.jar:?]
	at dev.lone.CinematicStudio.Main.onEnable(SourceFile:44) ~[CinematicStudio_2.0.0-indev-8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[00:00:43] [Server thread/INFO]: [CinematicStudio] Disabling CinematicStudio v2.0.0-indev-8
```

**Comment by Andre601** [comment]
Please provide your latest log through a paste site such as https://mclo.gs

**Comment by 44wrw44** [comment]
[latest.log](https://github.com/PluginBugs/Issues-CinematicStudio/files/15458291/latest.log)

**Comment by 44wrw44** [comment]
https://mclo.gs/BuZrMzY
