### ISSUE TITLE
Unsupported Minecraft 1.20.4

### ISSUE THREAD

**Issue by intersecato** [PluginBugs/Issues-CinematicStudio#93]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

intersecato

### What happened?

The plugin does not work on 1.20.4 with the latest version of LoneLibs and ProtocolLib.

### Steps to reproduce the issue

Self explanatory

### Server version

UniverseSpigot (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### CinematicsStudio Version

CinematicsStudio 2.0.0-indev-8

### ProtocolLib Version

ProtocolLib 5.2.0

### LoneLibs Version

LoneLibs 1.0.54

### Error (optional)

```shell
[10:51:34 ERROR]: [CinematicStudio] Failed to find nms implementation for: interface CinematicStudio.m.aK
[10:51:34 ERROR]: Error occurred while enabling CinematicStudio v2.0.0-indev-8 (Is it up to date?)
java.lang.RuntimeException: null
        at CinematicStudio.m.ar.a(SourceFile:138) ~[CinematicStudio_2.0.0-indev-8.jar:?]
        at CinematicStudio.m.ar.a(SourceFile:46) ~[CinematicStudio_2.0.0-indev-8.jar:?]
        at CinematicStudio.m.ar.a(SourceFile:37) ~[CinematicStudio_2.0.0-indev-8.jar:?]
        at CinematicStudio.m.aL.<init>(SourceFile:15) ~[CinematicStudio_2.0.0-indev-8.jar:?]
        at CinematicStudio.m.aL.a(SourceFile:38) ~[CinematicStudio_2.0.0-indev-8.jar:?]
        at dev.lone.CinematicStudio.Main.onEnable(SourceFile:44) ~[CinematicStudio_2.0.0-indev-8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[?:git-UniverseSpigot-"1954a51"]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[?:git-UniverseSpigot-"1954a51"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[?:git-UniverseSpigot-"1954a51"]
        at net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:137) ~[PluginManager.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:274) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[PluginManager.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1002) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:987) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:520) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[?:git-UniverseSpigot-"1954a51"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[10:51:34 INFO]: [CinematicStudio] Disabling CinematicStudio v2.0.0-indev-8
```

**Comment by Andre601** [comment]
Does this issue happen when using Paper? If not then this may be an issue with your particular fork and not CS.

**Comment by Andre601** [comment]
Also, please tick with your original issue (#92) as this is effectively the same problem as you reported there.

**Comment by intersecato** [comment]
> Does this issue happen when using Paper? If not then this may be an issue with your particular fork and not CS.

I carried out the necessary checks before reporting, but in any case it is a problem that has evidently been reported for several months and which is not being resolved.

**Comment by PSYCHEER** [comment]
As I tested, it's issue with last LoneLibs version, same as was CosmeticsCore before 1.0.54 or when you try using IA 3.6.3- with LoneLibs 1.0.54

**Comment by MattiaFioretti** [comment]
![image](https://github.com/PluginBugs/Issues-CinematicStudio/assets/84198050/2c505fec-9979-456b-8538-bca0a899fe18)
Now the plugin starts but with this error.

**Comment by PSYCHEER** [comment]
Okay, now plugin loads...but
https://mclo.gs/yloP6s6

**Comment by LoneDev6** [comment]
Bug of LoneLibs, will be fixed in the upcoming LoneLibs version.

**Comment by PSYCHEER** [comment]
Month after month, still doesnt work.
Tested on LoneLibs 1.0.56

**Comment by TH2403y** [comment]
Month after month, still doesnt work.
Tested on LoneLibs 1.0.56 +1

**Comment by intersecato** [comment]
Month after month, still doesnt work.
Tested on LoneLibs 1.0.56 +2

**Comment by Willi4mDev** [comment]
Month after month, still doesnt work.
Tested on LoneLibs 1.0.56 +3

**Comment by czychuuu** [comment]
Month after month, still doesnt work.
Tested on LoneLibs 1.0.57 +4

**Comment by CirrusPreeminent** [comment]
Month after month, still doesnt work.
Tested on LoneLibs 1.0.59 +5
